### ISSUE TITLE
Money is growing too fast

### ISSUE THREAD

**Issue by Petersoniel** [PrehistoricKingdom/feedback#215]
I found a bug and want to report it: I have only 6 mikroraptors in my zoo and the money is growing really fast. I made a video, so that you can see, what i mean:

https://user-images.githubusercontent.com/81023137/111870397-c93f7680-8984-11eb-81ef-3796c62f16af.mp4

Petersoniel

**Comment by PrehistoricKingdom** [comment]
There are most likely guests spawning in even though they aren't leaving the park entrance. This should be fixed in (0.2.2), and we will be reworking the economy system all throughout alpha/beta, right now money basically only goes up.

I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
