### ISSUE TITLE
Issues with GTX3080 ?

### ISSUE THREAD

**Issue by TyrealGaming** [PrehistoricKingdom/feedback#220]
I am not quite sure, if its a optimization thing but my GPU ist running at 100% , graphic changes doesnt matter it always run to the top even on lowest. (driver is on latest patch )

**Comment by JamieBurn99** [comment]
Don't worry dude, I have the same problem. I have a GTX 1660 and it runs at 100% on ultra settings and nearly 80 degrees. Turning down the settings and the resolution brought it down to 70 degrees and around 60% usage so I believe this is just an optimisation issue : )

**Comment by virtushda** [comment]
@TyrealGaming You're CPU-limited in that case.
What is your framerate?

CPU and GPU optimizations are planned, but you're always going to be limited by either your CPU or GPU if you have no framerate cap. :)

**Comment by TyrealGaming** [comment]
> @TyrealGaming You're CPU-limited in that case.
> What is your framerate?
> 
> CPU and GPU optimizations are planned, but you're always going to be limited by either your CPU or GPU if you have no framerate cap. :)

Framerate is by 180-200 FPS 

CPU is absolutly fine goes barely over 40%  , but yes a framerate cap would be the solution.

Just in case my Specs :
Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 CPUs), ~4.0GHz ( Watercooled but not overclocked so far )
NVIDIA GeForce RTX 3080 (MSI)
G.Skill Trident Z Neo Series, DDR4-3600, CL16 - 64 GB Quad-Kit (204 GB Pagefile ) 
And several SSD

**Comment by TyrealGaming** [comment]
The FPS limit solved the problem , I set a limit to 70 FPS with the Nvidia Inspector and now the game runs. But is still think that it needs to be optimized .

**Comment by PrehistoricKingdom** [comment]
We are introducing an in-game FPS limit setting to alleviate high GPU usage. This typically happens if you have VSync off, or if it is on but you cannot achieve the framerate that matches your monitor's refresh rate (i.e. if your refresh rate is 60 and your FPS is 45, or your refresh rate is 120 and your FPS is 100). Since it cannot actually achieve the target framerate and "rest" so to speak, it utilizes 100% of the GPU trying to reach it. This is typically normal, but we understand not everyone wants their GPU running hot/at 100% load.

We will be continually making GPU optimizations in the future to improve this further, and the FPS limiter will be in the next patch.

Thanks for your report!
