### ISSUE TITLE
re-positioning of water in the same place not possible.

### ISSUE THREAD

**Issue by Ebiline** [PrehistoricKingdom/feedback#227]
wenn man Wasser löscht oder  die Fläche planiert , kann man das Wasser nicht an der gleichen stelle wieder  setzen.
When you extinguish water or level the area, you can not put the water in the same place again.

**Comment by Xul666** [comment]
Ich hatte das selbe Problem. Man muss darauf achten, dass die ehemalige Wasserfläche komplett entfernt wurde! Sonst blockieren sich die Wasserflächen gegenseitig. Es bleiben "unterirdisch" manchmal kleine "Pfützen" erhalten, diese müssen entfernt werden! Am besten, mehrmals mit dem "Entfernen"-Tool über die Fläche gehen, dann klappt es...

I had the same issue. You have to make sure that the former water surface was completely removed! Otherwise the water surfaces block each other. There remain "underground" sometimes small "puddles", these must be removed! Best, go several times with the "Remove" tool over the surface, then it works...

**Comment by virtushda** [comment]
There are some edge cases where water will not be properly erased, even though it should be. I'll look into this further, and soon.

Additionally, raising the area a bit should get rid of any residual stubborn puddles.
