### ISSUE TITLE
The letters "B" and "N" is missing from the modular signs pieces

### ISSUE THREAD

**Issue by Windmiller215** [PrehistoricKingdom/feedback#268]
![20210321181509_1](https://user-images.githubusercontent.com/81104083/111914224-6aa3f680-8a71-11eb-9b34-c0b1d7fdb64d.jpg)

**Comment by Xul666** [comment]
Strange!
In my game everything looks fine at the moment...
![letters](https://user-images.githubusercontent.com/81046847/111918691-9e3d4b80-8a86-11eb-9254-9fa64f54cd08.JPG)

**Comment by PrehistoricKingdom** [comment]
It looks like they are being cut off on the right, probably due to that specific aspect/resolution. We will fix this but in the mean time you should be able to click those little slivers to select the items.

![image](https://user-images.githubusercontent.com/77504946/111920408-20b51380-8a65-11eb-919d-8f315ea73f0a.png)
