### ISSUE TITLE
Quick Reload 

### ISSUE THREAD

**Issue by Zenfroid** [PrehistoricKingdom/feedback#293]
When using quick reload, it does not quickly reload. I got stuck in the reload screen.

**Comment by PrehistoricKingdom** [comment]
Crashing/freezing during saves/load should be fixed in the most recent patch (0.2.2). We have temporarily disabled the quick load keybind though (F9), to prevent people accidentally clicking it. You can still load your quick save from the Options menu though (quick saves are named 'temp' in the menu).

I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
