### ISSUE TITLE
Objects of Shrubbery and Trees section no longer selectable when Stretched

### ISSUE THREAD

**Issue by FOXxTITAN** [PrehistoricKingdom/feedback#351]
Hello, I just found a bug for which I am not sure it has already been reported, I didn't find any other topic about it. So I apologize if this has already been reported.

It seems that all of the Shrubbery and Trees sections have a problem with the Scaling Edit.

When I stretch and distort objects in these sections, these objects are no longer selectable at all once deselected. Preventing them from being able to be deleted or modified in any way.
They appear in blue highlighted groups like all objects within the same group but are not selectable.

I have tried with the other sections of objects, they seem to work normally.
I tried on a backup from before the last patch. I can still select the trees or bushes in my enclosures but once stretched and deselected they no longer become selectable.
I tried reloading the save but it had no effect.

**Comment by Xul666** [comment]
I can confirm that. 
But this applies not only to trees and bushes, but also to other modular objects such as walls or roof elements. If you have rescaled these, it can happen that they can no longer be selected later, although they are still within the group and are marked blue when you select the group. It then doesn't matter from which camera angle you try. Only if you draw a larger frame over the object group, you can be lucky and the object will be captured and you can edit it again. 

If you save the game and reload it, the problem is solved, so my experience.
