### ISSUE TITLE
.exe is seen as a virus by AVG

### ISSUE THREAD

**Issue by switchkeys** [PrehistoricKingdom/feedback#360]
AVG keeps placing the .exe file in quarantaine, making it impossible to launch to the game

**Comment by PrehistoricKingdom** [comment]
Thanks for the report! You can whitelist the executable in AVG to let it launch.

We were not able to digitally sign this version of the exe unfortunately so AVG is probably seeing that it is an unknown executable and flagging it as bad just in case. You can override this in the AVG settings. In the future we will be digitally signing the executables so that it does not cause a false positive.

Thanks!
