### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NordiYT** [PrehistoricKingdom/feedback#487]
When set Buildings inside Trees or something they dont dissapear, it stands in it.

![Bild_2022-04-27_213802246](https://user-images.githubusercontent.com/104527852/165609589-d894f075-a6fe-4531-a91e-c467ddf42112.png)

**Comment by HanselReturns** [comment]
The game allows clipping in order to give the user more control on visual customisation.
It's up to the user to decide if he likes the aesthetic or not.
You will manually have to remove some objects, the game won't do this for you like in most other games.
But it allows for more freedom and creativity.
